# Generated by Django 4.0.4 on 2022-05-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_criminal_plaeofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminal',
            name='wantedInCountry',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
