# Generated by Django 4.0.4 on 2022-05-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_criminal_wantedincountry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminal',
            name='gender',
            field=models.CharField(default='Male', max_length=20),
        ),
    ]
