# Generated by Django 4.0.4 on 2022-05-24 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_criminal_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criminal',
            old_name='_id',
            new_name='crim_id',
        ),
    ]
